### ISSUE TITLE
New 'hf search'

### ISSUE THREAD

**Issue by MohammadSecure** [Proxmark/proxmark3#957] opened 2020-11-23 15:18 UTC
my idea is detect two each together cards,
i want have a custom search function that edited hf search until a after first run without
field interruption again run hf 14a info but between two hf 14a info , send halt command 0x50 until first card go to idle state. After that run hf 14a info for second to detect second card.

**Comment by pwpiwi** [comment] 2021-01-14 08:27
Duplicate of #954.

**Closed by pwpiwi** 2021-01-14 08:27 UTC
