### ISSUE TITLE
Proxmark slowness issue 

### ISSUE THREAD

**Issue by Kaicastledine** [Proxmark/proxmark3#485] opened 2017-11-15 20:19 UTC
Hello,

I've noticed with my proxmark that performance degrades after a few commands.
Im using the CLI on Mac OSX - High seirra 10.13.1

![image](https://user-images.githubusercontent.com/11678433/32857196-f7215414-ca3e-11e7-8f25-e1204397c597.png)

When using a Mifare s50 card 

hf search - Takes up to 30 seconds
hf mf - takes up to 1 min 23 seconds to lists commands
hf mf chk = ? - takes up to 1 min 57 seconds
hf mf nested 1 0 B ffffffffffff d - Takes 15 min 29 seconds ! 

Any ideas how I can troubleshoot what's causing the slowness ?

**Comment by pwpiwi** [comment] 2017-11-15 21:09
Duplicate of #283?

**Comment by Kaicastledine** [comment] 2017-11-16 09:25
Indeed, I've just read the whole issue post.
Thanks for the reference. 

Will keep posted on the other thread.

**Comment by pwpiwi** [comment] 2017-11-22 18:48
Closed in favor of #283

**Closed by pwpiwi** 2017-11-22 18:48 UTC
Labels: duplicate
